version: '3.9'
services:
    postgres_db:
      image: postgres:latest
      container_name: PostgresDB
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=mohamed
      ports:
        - '5432:5432'
